development:
  adapter: postgresql
  encoding: utf-8
  database: mtg_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf-8
  database: mtg_test
  pool: 5
  host: localhost